// Keepalive timer ID
let keepAliveTimer = null;
// Reconnection attempt counter for exponential backoff
let reconnectAttempts = 0;
// Image rate limiting
const imageRateLimits = new Map();
// Global message rate limit (shared for DoS mitigation)
let globalMessageRate = { count: 0, startTime: Date.now() };

// Define generateCode locally to avoid dependency on utils.js
function generateCode() {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < 16; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
    if (i % 4 === 3 && i < 15) result += '-';
  }
  return result;
}

let code = generateCode();
let clientId = Math.random().toString(36).substr(2, 9); // Default clientId for non-browser
let username = '';
let isInitiator = false;
let isConnected = false;
let maxClients = 2;
let totalClients = 0;
let peerConnections = new Map();
let dataChannels = new Map();
let connectionTimeouts = new Map();
let retryCounts = new Map();
const maxRetries = 2;
let candidatesQueues = new Map();
let processedMessageIds = new Set();
let usernames = new Map();
const messageRateLimits = new Map();
let codeSentToRandom = false;
let useRelay = false; // Flag for fallback to server relay
let token = ''; // Store JWT access token from server
let refreshToken = ''; // Store JWT refresh token from server

let keyPair; // ECDH keypair for E2E key exchange
let roomKey; // AES room key for E2E encryption (generated by initiator)

// Browser-specific variables and initializations
if (typeof window !== 'undefined') {
  // Update clientId and username from localStorage
  if (localStorage.getItem('clientId')) {
    clientId = localStorage.getItem('clientId');
  } else {
    localStorage.setItem('clientId', clientId);
  }
  username = localStorage.getItem('username')?.trim() || '';

  globalMessageRate.startTime = performance.now(); // Use performance.now() only in browser

  const statusElement = document.getElementById('status');
  const codeDisplayElement = document.getElementById('codeDisplay');
  const copyCodeButton = document.getElementById('copyCodeButton');
  const initialContainer = document.getElementById('initialContainer');
  const usernameContainer = document.getElementById('usernameContainer');
  const connectContainer = document.getElementById('connectContainer');
  const chatContainer = document.getElementById('chatContainer');
  const newSessionButton = document.getElementById('newSessionButton');
  const maxClientsContainer = document.getElementById('maxClientsContainer');
  const inputContainer = document.querySelector('.input-container');
  const messages = document.getElementById('messages');
  const cornerLogo = document.getElementById('cornerLogo');
  const button2 = document.getElementById('button2');
  const helpText = document.getElementById('helpText');
  const helpModal = document.getElementById('helpModal');

  const socket = new WebSocket('wss://signaling-server-zc6m.onrender.com');
  console.log('WebSocket created');

  // Generate ECDH keypair on load
  (async () => {
    keyPair = await window.crypto.subtle.generateKey(
      { name: 'ECDH', namedCurve: 'P-256' },
      true,
      ['deriveKey']
    );
  })();

  // Logo cycle animation
  let cycleTimeout;
  function triggerCycle() {
    if (cycleTimeout) clearTimeout(cycleTimeout);
    cornerLogo.classList.add('wink');
    cycleTimeout = setTimeout(() => {
      cornerLogo.classList.remove('wink');
    }, 500);
    setTimeout(() => triggerCycle(), 60000);
  }
  setTimeout(() => triggerCycle(), 60000);

  // Ensure maxClients UI is initialized after DOM is loaded
  document.addEventListener('DOMContentLoaded', () => {
    console.log('DOM loaded, initializing maxClients UI');
    initializeMaxClientsUI();
  });
}
